// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: findito.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_findito_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type FoundItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location       *Location              `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	FoundTimestamp int64                  `protobuf:"varint,5,opt,name=found_timestamp,json=foundTimestamp,proto3" json:"found_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FoundItem) Reset() {
	*x = FoundItem{}
	mi := &file_findito_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundItem) ProtoMessage() {}

func (x *FoundItem) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundItem.ProtoReflect.Descriptor instead.
func (*FoundItem) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{1}
}

func (x *FoundItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoundItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoundItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FoundItem) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *FoundItem) GetFoundTimestamp() int64 {
	if x != nil {
		return x.FoundTimestamp
	}
	return 0
}

type ReportFoundItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFoundItemRequest) Reset() {
	*x = ReportFoundItemRequest{}
	mi := &file_findito_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFoundItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFoundItemRequest) ProtoMessage() {}

func (x *ReportFoundItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFoundItemRequest.ProtoReflect.Descriptor instead.
func (*ReportFoundItemRequest) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{2}
}

func (x *ReportFoundItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportFoundItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportFoundItemRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type ReportFoundItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFoundItemResponse) Reset() {
	*x = ReportFoundItemResponse{}
	mi := &file_findito_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFoundItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFoundItemResponse) ProtoMessage() {}

func (x *ReportFoundItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFoundItemResponse.ProtoReflect.Descriptor instead.
func (*ReportFoundItemResponse) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{3}
}

func (x *ReportFoundItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ReportFoundItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportFoundItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchItemsAlongRouteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RoutePoints        []*Location            `protobuf:"bytes,1,rep,name=route_points,json=routePoints,proto3" json:"route_points,omitempty"`
	SearchRadiusMeters float64                `protobuf:"fixed64,2,opt,name=search_radius_meters,json=searchRadiusMeters,proto3" json:"search_radius_meters,omitempty"`
	MaxAgeSeconds      int64                  `protobuf:"varint,3,opt,name=max_age_seconds,json=maxAgeSeconds,proto3" json:"max_age_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchItemsAlongRouteRequest) Reset() {
	*x = SearchItemsAlongRouteRequest{}
	mi := &file_findito_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsAlongRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsAlongRouteRequest) ProtoMessage() {}

func (x *SearchItemsAlongRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsAlongRouteRequest.ProtoReflect.Descriptor instead.
func (*SearchItemsAlongRouteRequest) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{4}
}

func (x *SearchItemsAlongRouteRequest) GetRoutePoints() []*Location {
	if x != nil {
		return x.RoutePoints
	}
	return nil
}

func (x *SearchItemsAlongRouteRequest) GetSearchRadiusMeters() float64 {
	if x != nil {
		return x.SearchRadiusMeters
	}
	return 0
}

func (x *SearchItemsAlongRouteRequest) GetMaxAgeSeconds() int64 {
	if x != nil {
		return x.MaxAgeSeconds
	}
	return 0
}

type SearchItemsAlongRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FoundItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsAlongRouteResponse) Reset() {
	*x = SearchItemsAlongRouteResponse{}
	mi := &file_findito_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsAlongRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsAlongRouteResponse) ProtoMessage() {}

func (x *SearchItemsAlongRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsAlongRouteResponse.ProtoReflect.Descriptor instead.
func (*SearchItemsAlongRouteResponse) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{5}
}

func (x *SearchItemsAlongRouteResponse) GetItems() []*FoundItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_findito_proto protoreflect.FileDescriptor

const file_findito_proto_rawDesc = "" +
	"\n" +
	"\rfindito.proto\x12\x06server\"D\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\xa8\x01\n" +
	"\tFoundItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\blocation\x18\x04 \x01(\v2\x10.server.LocationR\blocation\x12'\n" +
	"\x0ffound_timestamp\x18\x05 \x01(\x03R\x0efoundTimestamp\"|\n" +
	"\x16ReportFoundItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12,\n" +
	"\blocation\x18\x03 \x01(\v2\x10.server.LocationR\blocation\"f\n" +
	"\x17ReportFoundItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xad\x01\n" +
	"\x1cSearchItemsAlongRouteRequest\x123\n" +
	"\froute_points\x18\x01 \x03(\v2\x10.server.LocationR\vroutePoints\x120\n" +
	"\x14search_radius_meters\x18\x02 \x01(\x01R\x12searchRadiusMeters\x12&\n" +
	"\x0fmax_age_seconds\x18\x03 \x01(\x03R\rmaxAgeSeconds\"H\n" +
	"\x1dSearchItemsAlongRouteResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.server.FoundItemR\x05items2\xca\x01\n" +
	"\x0eFinditoService\x12R\n" +
	"\x0fReportFoundItem\x12\x1e.server.ReportFoundItemRequest\x1a\x1f.server.ReportFoundItemResponse\x12d\n" +
	"\x15SearchItemsAlongRoute\x12$.server.SearchItemsAlongRouteRequest\x1a%.server.SearchItemsAlongRouteResponseB!Z\x1fgithub.com/Findito/server/protob\x06proto3"

var (
	file_findito_proto_rawDescOnce sync.Once
	file_findito_proto_rawDescData []byte
)

func file_findito_proto_rawDescGZIP() []byte {
	file_findito_proto_rawDescOnce.Do(func() {
		file_findito_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findito_proto_rawDesc), len(file_findito_proto_rawDesc)))
	})
	return file_findito_proto_rawDescData
}

var file_findito_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_findito_proto_goTypes = []any{
	(*Location)(nil),                      // 0: server.Location
	(*FoundItem)(nil),                     // 1: server.FoundItem
	(*ReportFoundItemRequest)(nil),        // 2: server.ReportFoundItemRequest
	(*ReportFoundItemResponse)(nil),       // 3: server.ReportFoundItemResponse
	(*SearchItemsAlongRouteRequest)(nil),  // 4: server.SearchItemsAlongRouteRequest
	(*SearchItemsAlongRouteResponse)(nil), // 5: server.SearchItemsAlongRouteResponse
}
var file_findito_proto_depIdxs = []int32{
	0, // 0: server.FoundItem.location:type_name -> server.Location
	0, // 1: server.ReportFoundItemRequest.location:type_name -> server.Location
	0, // 2: server.SearchItemsAlongRouteRequest.route_points:type_name -> server.Location
	1, // 3: server.SearchItemsAlongRouteResponse.items:type_name -> server.FoundItem
	2, // 4: server.FinditoService.ReportFoundItem:input_type -> server.ReportFoundItemRequest
	4, // 5: server.FinditoService.SearchItemsAlongRoute:input_type -> server.SearchItemsAlongRouteRequest
	3, // 6: server.FinditoService.ReportFoundItem:output_type -> server.ReportFoundItemResponse
	5, // 7: server.FinditoService.SearchItemsAlongRoute:output_type -> server.SearchItemsAlongRouteResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_findito_proto_init() }
func file_findito_proto_init() {
	if File_findito_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findito_proto_rawDesc), len(file_findito_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findito_proto_goTypes,
		DependencyIndexes: file_findito_proto_depIdxs,
		MessageInfos:      file_findito_proto_msgTypes,
	}.Build()
	File_findito_proto = out.File
	file_findito_proto_goTypes = nil
	file_findito_proto_depIdxs = nil
}
