// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: findito.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_findito_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type LocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,2,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_findito_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{1}
}

func (x *LocationUpdate) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *LocationUpdate) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type FoundItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location       *Location              `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	FoundTimestamp int64                  `protobuf:"varint,5,opt,name=found_timestamp,json=foundTimestamp,proto3" json:"found_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FoundItem) Reset() {
	*x = FoundItem{}
	mi := &file_findito_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundItem) ProtoMessage() {}

func (x *FoundItem) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundItem.ProtoReflect.Descriptor instead.
func (*FoundItem) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{2}
}

func (x *FoundItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoundItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoundItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FoundItem) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *FoundItem) GetFoundTimestamp() int64 {
	if x != nil {
		return x.FoundTimestamp
	}
	return 0
}

type ReportFoundItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFoundItemRequest) Reset() {
	*x = ReportFoundItemRequest{}
	mi := &file_findito_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFoundItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFoundItemRequest) ProtoMessage() {}

func (x *ReportFoundItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFoundItemRequest.ProtoReflect.Descriptor instead.
func (*ReportFoundItemRequest) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{3}
}

func (x *ReportFoundItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportFoundItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportFoundItemRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type ReportFoundItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFoundItemResponse) Reset() {
	*x = ReportFoundItemResponse{}
	mi := &file_findito_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFoundItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFoundItemResponse) ProtoMessage() {}

func (x *ReportFoundItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFoundItemResponse.ProtoReflect.Descriptor instead.
func (*ReportFoundItemResponse) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{4}
}

func (x *ReportFoundItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ReportFoundItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportFoundItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchItemsAlongRouteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RoutePoints        []*Location            `protobuf:"bytes,1,rep,name=route_points,json=routePoints,proto3" json:"route_points,omitempty"`
	SearchRadiusMeters float64                `protobuf:"fixed64,2,opt,name=search_radius_meters,json=searchRadiusMeters,proto3" json:"search_radius_meters,omitempty"`
	MaxAgeSeconds      int64                  `protobuf:"varint,3,opt,name=max_age_seconds,json=maxAgeSeconds,proto3" json:"max_age_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchItemsAlongRouteRequest) Reset() {
	*x = SearchItemsAlongRouteRequest{}
	mi := &file_findito_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsAlongRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsAlongRouteRequest) ProtoMessage() {}

func (x *SearchItemsAlongRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsAlongRouteRequest.ProtoReflect.Descriptor instead.
func (*SearchItemsAlongRouteRequest) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{5}
}

func (x *SearchItemsAlongRouteRequest) GetRoutePoints() []*Location {
	if x != nil {
		return x.RoutePoints
	}
	return nil
}

func (x *SearchItemsAlongRouteRequest) GetSearchRadiusMeters() float64 {
	if x != nil {
		return x.SearchRadiusMeters
	}
	return 0
}

func (x *SearchItemsAlongRouteRequest) GetMaxAgeSeconds() int64 {
	if x != nil {
		return x.MaxAgeSeconds
	}
	return 0
}

type SearchItemsAlongRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FoundItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsAlongRouteResponse) Reset() {
	*x = SearchItemsAlongRouteResponse{}
	mi := &file_findito_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsAlongRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsAlongRouteResponse) ProtoMessage() {}

func (x *SearchItemsAlongRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findito_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsAlongRouteResponse.ProtoReflect.Descriptor instead.
func (*SearchItemsAlongRouteResponse) Descriptor() ([]byte, []int) {
	return file_findito_proto_rawDescGZIP(), []int{6}
}

func (x *SearchItemsAlongRouteResponse) GetItems() []*FoundItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_findito_proto protoreflect.FileDescriptor

const file_findito_proto_rawDesc = "" +
	"\n" +
	"\rfindito.proto\x12\afindito\"D\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\\\n" +
	"\x0eLocationUpdate\x12-\n" +
	"\blocation\x18\x01 \x01(\v2\x11.findito.LocationR\blocation\x12\x1b\n" +
	"\tradius_km\x18\x02 \x01(\x01R\bradiusKm\"\xa9\x01\n" +
	"\tFoundItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\blocation\x18\x04 \x01(\v2\x11.findito.LocationR\blocation\x12'\n" +
	"\x0ffound_timestamp\x18\x05 \x01(\x03R\x0efoundTimestamp\"}\n" +
	"\x16ReportFoundItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12-\n" +
	"\blocation\x18\x03 \x01(\v2\x11.findito.LocationR\blocation\"f\n" +
	"\x17ReportFoundItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xae\x01\n" +
	"\x1cSearchItemsAlongRouteRequest\x124\n" +
	"\froute_points\x18\x01 \x03(\v2\x11.findito.LocationR\vroutePoints\x120\n" +
	"\x14search_radius_meters\x18\x02 \x01(\x01R\x12searchRadiusMeters\x12&\n" +
	"\x0fmax_age_seconds\x18\x03 \x01(\x03R\rmaxAgeSeconds\"I\n" +
	"\x1dSearchItemsAlongRouteResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.findito.FoundItemR\x05items2\x93\x02\n" +
	"\x0eFinditoService\x12T\n" +
	"\x0fReportFoundItem\x12\x1f.findito.ReportFoundItemRequest\x1a .findito.ReportFoundItemResponse\x12f\n" +
	"\x15SearchItemsAlongRoute\x12%.findito.SearchItemsAlongRouteRequest\x1a&.findito.SearchItemsAlongRouteResponse\x12C\n" +
	"\x10TrackNearbyItems\x12\x17.findito.LocationUpdate\x1a\x12.findito.FoundItem(\x010\x01B!Z\x1fgithub.com/Findito/server/protob\x06proto3"

var (
	file_findito_proto_rawDescOnce sync.Once
	file_findito_proto_rawDescData []byte
)

func file_findito_proto_rawDescGZIP() []byte {
	file_findito_proto_rawDescOnce.Do(func() {
		file_findito_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findito_proto_rawDesc), len(file_findito_proto_rawDesc)))
	})
	return file_findito_proto_rawDescData
}

var file_findito_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_findito_proto_goTypes = []any{
	(*Location)(nil),                      // 0: findito.Location
	(*LocationUpdate)(nil),                // 1: findito.LocationUpdate
	(*FoundItem)(nil),                     // 2: findito.FoundItem
	(*ReportFoundItemRequest)(nil),        // 3: findito.ReportFoundItemRequest
	(*ReportFoundItemResponse)(nil),       // 4: findito.ReportFoundItemResponse
	(*SearchItemsAlongRouteRequest)(nil),  // 5: findito.SearchItemsAlongRouteRequest
	(*SearchItemsAlongRouteResponse)(nil), // 6: findito.SearchItemsAlongRouteResponse
}
var file_findito_proto_depIdxs = []int32{
	0, // 0: findito.LocationUpdate.location:type_name -> findito.Location
	0, // 1: findito.FoundItem.location:type_name -> findito.Location
	0, // 2: findito.ReportFoundItemRequest.location:type_name -> findito.Location
	0, // 3: findito.SearchItemsAlongRouteRequest.route_points:type_name -> findito.Location
	2, // 4: findito.SearchItemsAlongRouteResponse.items:type_name -> findito.FoundItem
	3, // 5: findito.FinditoService.ReportFoundItem:input_type -> findito.ReportFoundItemRequest
	5, // 6: findito.FinditoService.SearchItemsAlongRoute:input_type -> findito.SearchItemsAlongRouteRequest
	1, // 7: findito.FinditoService.TrackNearbyItems:input_type -> findito.LocationUpdate
	4, // 8: findito.FinditoService.ReportFoundItem:output_type -> findito.ReportFoundItemResponse
	6, // 9: findito.FinditoService.SearchItemsAlongRoute:output_type -> findito.SearchItemsAlongRouteResponse
	2, // 10: findito.FinditoService.TrackNearbyItems:output_type -> findito.FoundItem
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_findito_proto_init() }
func file_findito_proto_init() {
	if File_findito_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findito_proto_rawDesc), len(file_findito_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findito_proto_goTypes,
		DependencyIndexes: file_findito_proto_depIdxs,
		MessageInfos:      file_findito_proto_msgTypes,
	}.Build()
	File_findito_proto = out.File
	file_findito_proto_goTypes = nil
	file_findito_proto_depIdxs = nil
}
